services:
  project-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass variables from the .env file
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production